import { Workspace, User, Video, Tag, AnalyticsFilter } from '../types';

export const MOCK_WORKSPACES: Workspace[] = [
  {
    id: 'w1',
    name: 'Kayak',
    username: '@kayak.skills',
    logo: 'https://picsum.photos/seed/kayak/100',
    workspaceType: 'Skills',
  },
  {
    id: 'w2',
    name: 'Emirates',
    username: '@Emirates.social',
    logo: 'https://picsum.photos/seed/emirates/100',
    workspaceType: 'Social',
  },
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alex Carter',
  username: '@alexcreates',
  bio: 'Content creator | Tech & Lifestyle | Partnered with top brands 🚀',
  profileImage: 'https://picsum.photos/seed/alex/200',
  bannerImage: 'https://picsum.photos/seed/banner/800/300',
  followers: 48200,
  totalViews: 1230000,
  workspaces: MOCK_WORKSPACES,
  activeWorkspaceId: 'w1',
  kycCompleted: false,
  country: 'US',
  language: 'en',
};

const generateTimeSeries = (count: number, labelFn: (i: number) => string) =>
  Array.from({ length: count }, (_, i) => ({
    label: labelFn(i),
    views: Math.floor(Math.random() * 50000) + 5000,
    income: Math.floor(Math.random() * 500) + 50,
  }));

const makeAnalytics = (seed: number) => ({
  income: seed * 127,
  views: seed * 4300,
  likes: seed * 210,
  comments: seed * 43,
  shares: seed * 88,
  watchTime: seed * 32400,
  totalTraffic: seed * 5100,
  referralLink: `https://creatorportal.io/ref/${seed}abc`,
  weekly: generateTimeSeries(7, (i) => ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][i]),
  monthly: generateTimeSeries(4, (i) => `W${i + 1}`),
  yearly: generateTimeSeries(12, (i) =>
    ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][i]
  ),
});

export const MOCK_VIDEOS: Video[] = [
  {
    id: 'v1',
    title: 'NovaBrand Q2 Product Launch',
    description: 'Showcasing the new NovaBrand X9 series with full feature walkthrough.',
    thumbnailUrl: 'https://picsum.photos/seed/v1/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'live',
    tags: [{ id: 't1', label: 'Product' }, { id: 't3', label: 'Tech' }],
    cta: { id: 'cta1', type: 'redirect', label: 'Shop Now', url: 'https://novabrand.com/shop' },
    workspaceId: 'w1',
    createdAt: '2025-04-10T10:00:00Z',
    duration: 62,
    analytics: makeAnalytics(12),
  },
  {
    id: 'v2',
    title: 'Behind the Scenes — NovaBrand Photoshoot',
    description: 'Exclusive BTS footage from our latest brand campaign.',
    thumbnailUrl: 'https://picsum.photos/seed/v2/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'pending',
    tags: [{ id: 't2', label: 'BTS' }, { id: 't4', label: 'Brand' }],
    workspaceId: 'w1',
    createdAt: '2025-04-22T14:30:00Z',
    duration: 45,
    analytics: makeAnalytics(5),
  },
  {
    id: 'v3',
    title: 'NovaBrand Lifestyle Campaign',
    description: 'A lifestyle video showing the brand in everyday scenarios.',
    thumbnailUrl: 'https://picsum.photos/seed/v3/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'rejected',
    tags: [{ id: 't5', label: 'Lifestyle' }],
    workspaceId: 'w1',
    createdAt: '2025-03-18T09:00:00Z',
    duration: 30,
    analytics: makeAnalytics(2),
  },
  {
    id: 'v4',
    title: 'Unboxing — NovaBrand Limited Edition',
    description: 'First look at the limited edition collector package.',
    thumbnailUrl: 'https://picsum.photos/seed/v4/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'revise',
    tags: [{ id: 't1', label: 'Product' }, { id: 't6', label: 'Unboxing' }],
    workspaceId: 'w1',
    createdAt: '2025-04-28T11:00:00Z',
    duration: 75,
    analytics: makeAnalytics(7),
  },
  {
    id: 'v5',
    title: 'Kayak Skills — Pro Paddle Technique',
    description: 'Master the forward stroke with certified instructor tips.',
    thumbnailUrl: 'https://picsum.photos/seed/v5/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'live',
    tags: [{ id: 't7', label: 'Tutorial' }, { id: 't5', label: 'Lifestyle' }],
    cta: { id: 'cta5', type: 'redirect', label: 'Book a Session', url: 'https://kayak.skills/book' },
    workspaceId: 'w1',
    createdAt: '2025-05-01T08:00:00Z',
    duration: 58,
    analytics: makeAnalytics(18),
  },
  {
    id: 'v6',
    title: 'Top 5 Whitewater Safety Tips',
    description: 'Essential safety rules every kayaker must know before hitting rapids.',
    thumbnailUrl: 'https://picsum.photos/seed/v6/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'live',
    tags: [{ id: 't8', label: 'Review' }, { id: 't3', label: 'Tech' }],
    cta: { id: 'cta6', type: 'redirect', label: 'Learn More', url: 'https://kayak.skills/safety' },
    workspaceId: 'w1',
    createdAt: '2025-04-30T10:15:00Z',
    duration: 90,
    analytics: makeAnalytics(22),
  },
  {
    id: 'v7',
    title: 'Gear Review — Inflatable Kayak 2025',
    description: 'We tested 6 inflatable kayaks so you don\'t have to.',
    thumbnailUrl: 'https://picsum.photos/seed/v7/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'pending',
    tags: [{ id: 't8', label: 'Review' }, { id: 't6', label: 'Unboxing' }],
    workspaceId: 'w1',
    createdAt: '2025-05-03T09:30:00Z',
    duration: 110,
    analytics: makeAnalytics(3),
  },
  {
    id: 'v8',
    title: 'Morning Paddle Routine',
    description: 'Start your day right with this 15-minute warm-up on the water.',
    thumbnailUrl: 'https://picsum.photos/seed/v8/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'live',
    tags: [{ id: 't5', label: 'Lifestyle' }],
    cta: { id: 'cta8', type: 'redirect', label: 'Join the Community', url: 'https://kayak.skills/community' },
    workspaceId: 'w1',
    createdAt: '2025-04-15T06:00:00Z',
    duration: 47,
    analytics: makeAnalytics(31),
  },
  {
    id: 'v9',
    title: 'Kayak Camping — 3 Day Coastal Trip',
    description: 'Follow us on a stunning 3-day sea kayak camping adventure.',
    thumbnailUrl: 'https://picsum.photos/seed/v9/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'live',
    tags: [{ id: 't5', label: 'Lifestyle' }, { id: 't9', label: 'Event' }],
    cta: { id: 'cta9', type: 'redirect', label: 'Watch Full Series', url: 'https://kayak.skills/series' },
    workspaceId: 'w1',
    createdAt: '2025-04-05T12:00:00Z',
    duration: 180,
    analytics: makeAnalytics(44),
  },
  {
    id: 'v10',
    title: 'Rolling Technique — Beginner to Advanced',
    description: 'Step-by-step guide to nailing your kayak roll in any conditions.',
    thumbnailUrl: 'https://picsum.photos/seed/v10/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'rejected',
    tags: [{ id: 't7', label: 'Tutorial' }],
    workspaceId: 'w1',
    createdAt: '2025-03-28T14:00:00Z',
    duration: 73,
    analytics: makeAnalytics(1),
  },
  {
    id: 'v11',
    title: 'Partner Spotlight — Paddle Pro Gear',
    description: 'Exclusive partnership reveal with Paddle Pro — 20% off for our community.',
    thumbnailUrl: 'https://picsum.photos/seed/v11/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'live',
    tags: [{ id: 't4', label: 'Brand' }, { id: 't1', label: 'Product' }],
    cta: { id: 'cta11', type: 'redirect', label: 'Shop the Deal', url: 'https://paddlepro.com/kayak' },
    workspaceId: 'w1',
    createdAt: '2025-05-02T11:00:00Z',
    duration: 55,
    analytics: makeAnalytics(27),
  },
  {
    id: 'v12',
    title: 'Competition Recap — National Kayak Championships',
    description: 'Highlights and interviews from this year\'s national championships.',
    thumbnailUrl: 'https://picsum.photos/seed/v12/400/720',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    status: 'revise',
    tags: [{ id: 't9', label: 'Event' }, { id: 't10', label: 'Interview' }],
    workspaceId: 'w1',
    createdAt: '2025-04-20T16:00:00Z',
    duration: 95,
    analytics: makeAnalytics(9),
  },
];

export const PREDEFINED_TAGS: Tag[] = [
  { id: 't1', label: 'Product' },
  { id: 't2', label: 'BTS' },
  { id: 't3', label: 'Tech' },
  { id: 't4', label: 'Brand' },
  { id: 't5', label: 'Lifestyle' },
  { id: 't6', label: 'Unboxing' },
  { id: 't7', label: 'Tutorial' },
  { id: 't8', label: 'Review' },
  { id: 't9', label: 'Event' },
  { id: 't10', label: 'Interview' },
];

export const TAG_CATEGORIES: { id: string; name: string; color: string; tags: Tag[] }[] = [
  {
    id: 'tc1',
    name: 'Content Type',
    color: '#874FE1',
    tags: [
      { id: 't6', label: 'Unboxing' },
      { id: 't7', label: 'Tutorial' },
      { id: 't8', label: 'Review' },
      { id: 'tc1_t1', label: 'Vlog' },
      { id: 'tc1_t2', label: 'Short Film' },
      { id: 'tc1_t3', label: 'Behind the Scenes' },
    ],
  },
  {
    id: 'tc2',
    name: 'Industry',
    color: '#0099FF',
    tags: [
      { id: 't3', label: 'Tech' },
      { id: 't5', label: 'Lifestyle' },
      { id: 't9', label: 'Event' },
      { id: 'tc2_t1', label: 'Fashion' },
      { id: 'tc2_t2', label: 'Food & Drink' },
      { id: 'tc2_t3', label: 'Health' },
      { id: 'tc2_t4', label: 'Finance' },
    ],
  },
  {
    id: 'tc3',
    name: 'Audience',
    color: '#E06800',
    tags: [
      { id: 'tc3_t1', label: 'Gen Z' },
      { id: 'tc3_t2', label: 'Millennials' },
      { id: 'tc3_t3', label: 'Gen X' },
      { id: 'tc3_t4', label: 'Business' },
      { id: 'tc3_t5', label: 'Students' },
      { id: 'tc3_t6', label: 'Parents' },
    ],
  },
  {
    id: 'tc4',
    name: 'Platform',
    color: '#02C121',
    tags: [
      { id: 'tc4_t1', label: 'TikTok' },
      { id: 'tc4_t2', label: 'Instagram' },
      { id: 'tc4_t3', label: 'YouTube' },
      { id: 'tc4_t4', label: 'Facebook' },
      { id: 'tc4_t5', label: 'Twitter/X' },
    ],
  },
  {
    id: 'tc5',
    name: 'Campaign Type',
    color: '#FE6A00',
    tags: [
      { id: 'tc5_t1', label: 'Brand Awareness' },
      { id: 'tc5_t2', label: 'Product Launch' },
      { id: 'tc5_t3', label: 'Seasonal' },
      { id: 'tc5_t4', label: 'Sponsored' },
      { id: 'tc5_t5', label: 'Collaboration' },
    ],
  },
];

export const PREDEFINED_CTA_TYPES = [
  { id: 'redirect', label: 'Redirect Link' },
  { id: 'file', label: 'File Download' },
];

export const PREDEFINED_CTAS: {
  id: string;
  ctaCategory: string;
  name: string;
  label: string;
  icon: string;
  color: string;
  type: 'redirect' | 'file';
  url: string;
}[] = [
  {
    id: 'cta_detail_page',
    ctaCategory: 'Dynamic CTA',
    name: 'Detail Page',
    label: 'Learn more about this property',
    icon: 'call-outline',
    color: '#B8926A',
    type: 'redirect',
    url: 'https://creatorportal.io/detail',
  },
  {
    id: 'cta_whatsapp',
    ctaCategory: 'Fixed CTA',
    name: 'Primary WhatsApp',
    label: 'Chat with us now',
    icon: 'headset-outline',
    color: '#05A41E',
    type: 'redirect',
    url: 'https://wa.me/1234567890',
  },
  {
    id: 'cta_newsletter',
    ctaCategory: 'Fixed CTA',
    name: 'Newsletter',
    label: 'Join Our Newsletter',
    icon: 'reader-outline',
    color: '#F0B429',
    type: 'redirect',
    url: 'https://creatorportal.io/newsletter',
  },
  {
    id: 'cta_waitlist',
    ctaCategory: 'Fixed CTA',
    name: 'Waitlist',
    label: 'Waitlist',
    icon: 'mail-outline',
    color: '#6FCF4A',
    type: 'redirect',
    url: 'https://creatorportal.io/waitlist',
  },
  {
    id: 'cta_book_demo',
    ctaCategory: 'Fixed CTA',
    name: 'Book a Demo',
    label: 'Schedule a Demo',
    icon: 'calendar-outline',
    color: '#874FE1',
    type: 'redirect',
    url: 'https://creatorportal.io/demo',
  },
  {
    id: 'cta_shop_now',
    ctaCategory: 'Fixed CTA',
    name: 'Shop Now',
    label: 'Shop Now',
    icon: 'cart-outline',
    color: '#E06800',
    type: 'redirect',
    url: 'https://creatorportal.io/shop',
  },
];

export const VALID_INVITE_CODE = 'CREATOR2025';

export const ANALYTICS_FILTERS: AnalyticsFilter[] = ['1W', '4W', '1Y', 'MTD', 'QTD', 'YTD', 'ALL'];

export const COUNTRIES: { name: string; flag: string; code: string }[] = [
  { name: 'America (US)', flag: '🇺🇸', code: 'US' },
  { name: 'Afghanistan', flag: '🇦🇫', code: 'AF' },
  { name: 'Algeria', flag: '🇩🇿', code: 'DZ' },
  { name: 'Argentina', flag: '🇦🇷', code: 'AR' },
  { name: 'Australia', flag: '🇦🇺', code: 'AU' },
  { name: 'Austria', flag: '🇦🇹', code: 'AT' },
  { name: 'Bangladesh', flag: '🇧🇩', code: 'BD' },
  { name: 'Belgium', flag: '🇧🇪', code: 'BE' },
  { name: 'Brazil', flag: '🇧🇷', code: 'BR' },
  { name: 'Canada', flag: '🇨🇦', code: 'CA' },
  { name: 'China', flag: '🇨🇳', code: 'CN' },
  { name: 'Egypt', flag: '🇪🇬', code: 'EG' },
  { name: 'France', flag: '🇫🇷', code: 'FR' },
  { name: 'Germany', flag: '🇩🇪', code: 'DE' },
  { name: 'India', flag: '🇮🇳', code: 'IN' },
  { name: 'Indonesia', flag: '🇮🇩', code: 'ID' },
  { name: 'Italy', flag: '🇮🇹', code: 'IT' },
  { name: 'Japan', flag: '🇯🇵', code: 'JP' },
  { name: 'Jordan', flag: '🇯🇴', code: 'JO' },
  { name: 'Kenya', flag: '🇰🇪', code: 'KE' },
  { name: 'Malaysia', flag: '🇲🇾', code: 'MY' },
  { name: 'Mexico', flag: '🇲🇽', code: 'MX' },
  { name: 'Netherlands', flag: '🇳🇱', code: 'NL' },
  { name: 'Nigeria', flag: '🇳🇬', code: 'NG' },
  { name: 'Pakistan', flag: '🇵🇰', code: 'PK' },
  { name: 'Philippines', flag: '🇵🇭', code: 'PH' },
  { name: 'Portugal', flag: '🇵🇹', code: 'PT' },
  { name: 'Russia', flag: '🇷🇺', code: 'RU' },
  { name: 'Saudi Arabia', flag: '🇸🇦', code: 'SA' },
  { name: 'South Africa', flag: '🇿🇦', code: 'ZA' },
  { name: 'Spain', flag: '🇪🇸', code: 'ES' },
  { name: 'Sweden', flag: '🇸🇪', code: 'SE' },
  { name: 'Switzerland', flag: '🇨🇭', code: 'CH' },
  { name: 'Turkey', flag: '🇹🇷', code: 'TR' },
  { name: 'UAE', flag: '🇦🇪', code: 'AE' },
  { name: 'United Kingdom', flag: '🇬🇧', code: 'GB' },
];

export const LANGUAGES: { name: string; flag: string; native: string }[] = [
  { name: 'English (US)',       flag: '🇺🇸', native: 'English' },
  { name: 'Arabic (UAE)',       flag: '🇦🇪', native: 'العربية' },
  { name: 'Spanish (Spain)',    flag: '🇪🇸', native: 'Español' },
  { name: 'Hindi (India)',      flag: '🇮🇳', native: 'हिन्दी' },
  { name: 'Italian (Italy)',    flag: '🇮🇹', native: 'Italiano' },
  { name: 'German (Germany)',   flag: '🇩🇪', native: 'Deutsch' },
  { name: 'Swiss (Switzerland)',flag: '🇨🇭', native: 'Schweizerdeutsch' },
  { name: 'French (France)',    flag: '🇫🇷', native: 'Français' },
  { name: 'Portuguese',         flag: '🇵🇹', native: 'Português' },
  { name: 'Urdu (Pakistan)',    flag: '🇵🇰', native: 'اردو' },
  { name: 'Turkish',            flag: '🇹🇷', native: 'Türkçe' },
  { name: 'Japanese',           flag: '🇯🇵', native: '日本語' },
  { name: 'Chinese',            flag: '🇨🇳', native: '中文' },
  { name: 'Russian',            flag: '🇷🇺', native: 'Русский' },
  { name: 'Malay',              flag: '🇲🇾', native: 'Bahasa Melayu' },
];
